#!/usr/bin/env python3

"""Main program for DECnet node.
"""

import sys
if sys.version_info[0] < 3 or sys.version_info[1] < 3:
    print ("PyDECnet requires Python 3.3 or later")
    sys.exit (1)

import decnet.main

decnet.main.main ()
